apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
type: Opaque
data:
  requests-ca-bundle: {{ .Values.REQUESTS_CA_BUNDLE | b64enc }}
  domain-name: {{ .Values.DOMAIN_NAME | b64enc }}
  preferred-url-scheme: {{ .Values.PREFERRED_URL_SCHEME | b64enc  }}
  dex-client-id: {{ .Values.DEX_CLIENT_ID | b64enc }}
  dex-client-secret: {{ .Values.DEX_CLIENT_SECRET | b64enc }}
  secret-key: {{ .Values.SECRET_KEY | b64enc }}
