apiVersion: v1
kind: Service
metadata:
  name: {{ include "virtletdash.fullname" . }}
  labels:
{{ include "virtletdash.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetport }}
      protocol: TCP
      name: virtport
  selector:
    app.kubernetes.io/name: {{ include "virtletdash.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
